### ISSUE TITLE
Add default location setting (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica-storage-service#211]
Merge work from https://github.com/JiscRDSS/archivematica-storage-service/pull/8 and https://github.com/JiscRDSS/archivematica-storage-service/pull/8/ into core.

This provides a default location setting in the storage service.

Related AM issue: https://github.com/artefactual/archivematica/issues/669

**Comment by lower29** [comment]
I have a dev branch based on `qa/0.x` ready to go for this change, but I don't have permission to push.

The branch includes the changes from https://github.com/JiscRDSS/archivematica-storage-service/pull/8 and https://github.com/JiscRDSS/archivematica-storage-service/pull/11 (which was a fix to 8) as well as a minor fix to a typo I spotted when I was reviewing the commits. Since the change for 11 is actually a fix for 8, I've squashed the three commits into one.

**Comment by sevein** [comment]
Richard, you can fork the repo via GitHub, push the branch to your own remote and then submit the pull request.

**Comment by lower29** [comment]
Yeah, Justin has suggested I use the JiscRDSS fork to prepare the branch.

**Comment by sevein** [comment]
Fixed in #212.

**Comment by sallain** [comment]
I've only tested this with a default AIP storage location, but it seems to be working well - extensive testing on our servers with "Store AIP location" set to "Default location" hasn't resulted in any errors, including when the default location is changed in the Storage Service.
