### ISSUE TITLE
Problem: Create Key page is unclear

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica-storage-service#264]
The two fields in the Create Key page are labelled "Name real" and "Name email." It would be more clear if they were labelled "Name" and "Email."

**Comment by jrwdunham** [comment]
I agree with you. I think I did that for a reason. I think the reason was that that is what GPG calls them. There are some aspects of GPG's key(chain) model that we are simplifying here. Maybe we should make the fields make more sense in our interface (as you say) but have tooltips or something that make the mapping to GPG keys make sense for users familiar with that model?

**Comment by jrwdunham** [comment]
Should be fixed by https://github.com/artefactual/archivematica-storage-service/pull/272

**Comment by currmie** [comment]
Verified GPG key GUI enhancements; related changes / updates to AM Storage Service docs in progress.

**Comment by currmie** [comment]
UI dev fix verified. AM ss0.11 docs updated and ready for review @sromkey
