### ISSUE TITLE
Problem: test user is always created

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#286]
Storage Service creates a `test` user automatically using the same password: `test`. It is created after the `postdb_sync` (aka `migrate` in recent versions of Django) signal is dispatched. Here's our callback:

https://github.com/artefactual/archivematica-storage-service/blob/2cc49f7debaeeb77bccb77e99c5844dc41b8b845/storage_service/common/models.py#L14-L21

As a result, the `test` user is made available when Storage Service is installed for the first time but also during release upgrades when the `manage.py migrate` command is executed. I think this is highly undesirable from a security point of view. If you find an instance of Storage Service in the wild there is a big chance that you can log in successfully using the default test user.

The user can manually delete the user after installing the application but the upgrade process will re-create it which is something that the user will not expect. The only effective way to void this behaviour today seems to be to change the password of the user. In the docs, we recommend the following:

> It is recommended that you also modify the test user and change the default password. This will also result in a new API key for the test user but that does not need to be copied to the clipboard in this instance.

I don't think that we're making clear very clear what's the actual behaviour.

My preference would be to stop creating the test user.

**Comment by sevein** [comment]
If we fix this our test suite will break because it relies on the fact that the test user is automatically created. I fixed that in our RDSS fork, just by adding the following two objects to the `base.json` fixture:

```json
[
{
    "fields": {
        "username": "test",
        "first_name": "",
        "last_name": "",
        "is_active": true,
        "is_superuser": true,
        "is_staff": true,
        "last_login": null,
        "groups": [],
        "user_permissions": [],
        "password": "pbkdf2_sha256$20000$KtBsDJ1Efvp0$Hyvx9WvqBq2rNZX8DW1dpo8WdsEats9qc0U/NlK/Gq8=",
        "email": "test@test.com",
        "date_joined": "2017-12-06T21:16:42.772Z"
    },
    "model": "auth.user",
    "pk": 1
},
{
    "fields": {
        "user": 1,
        "key": "test",
        "created": "2017-12-06T21:16:42.838Z"
    },
    "model": "tastypie.apikey",
    "pk": 1
},
]
```

**Comment by sevein** [comment]
Not happening in SS 0.11.

**Comment by sromkey** [comment]
I believe @currmie is testing and documenting this.

**Comment by currmie** [comment]
@sevein @sromkey - yep, I'm on it;  see 185 in archivematica-docs for corresponding doc issue

**Comment by currmie** [comment]
Feedback for @sevein:
-I was able to manually install latest AM using packages on Ubuntu 16.04.
-During post-install configuration, I was able to bring up the Storage Service on port 8000.
-Made sure that I emptied cache and did a hard reload in browser; result upon loading storage service IP address in local development setup = Log in to Storage Service portal. Strange thing is that it's still remembering test user account credentials even though I installed on a clean VM.
-Leads me to believe that the default test user account is still being created automatically. 
-Any thoughts on what I can try next in my local setup @sevein?
-Also, could you outline what the expected behaviour should actually be for this issue? Thx in advance!

**Comment by sevein** [comment]
Maybe what's confusing is that our development environment is creating the same user so it's hard tell where is it coming from. See:

https://github.com/artefactual-labs/am/blob/f3e51ee2d9fa46ef6b921fa46f6884611228ad52/compose/Makefile#L33-L42

One possible way to confirm that this is working is to locally update the `Makefile` linked above with updated parameters for the `create_user` command, i.e. `--username=foobar`, `--password=foobar`, `--api-key=foobar`. You would also need to update [these lines](https://github.com/artefactual-labs/am/blob/f3e51ee2d9fa46ef6b921fa46f6884611228ad52/compose/Makefile#L90-L91) accordingly. Once you're done, bootstrap the environment again with `make bootstrap` and `make restart-am-services`. It should all work with the only difference that the user created in am.git is now `foobar` instead of `test`. Additionally, you should be able to confirm that SS does not have a `test` user when you list the users in the Admin page.

Let me know if you need help with the instructions above. We could do this together via Slack.

**Comment by currmie** [comment]
Thanks @sevein! I will give this a shot and ping you if I run into a problem.

**Comment by currmie** [comment]
Hi @sevein  ! Latest info. on QA/testing...

Per your instructions, I am able to to confirm that SS does not have a test user when I list the users in the Admin page. 

However,  I cannot  login onto the development environment as  user 'foobar'  after I updated the Makefile and bootstrapped the environment again with make bootstrap and make restart-am-services.

Seems like this is the expected behaviour that we are looking for in the fix per your instructions?!

**Comment by sevein** [comment]
> However, I cannot login onto the development environment as user 'foobar' after I updated the Makefile and bootstrapped the environment again with make bootstrap and make restart-am-services.

We created the `foobar` user in SS.
Dashboard is still using `test` unless you change that too, here:

https://github.com/artefactual-labs/am/blob/f3e51ee2d9fa46ef6b921fa46f6884611228ad52/compose/Makefile#L82-L85

So yeah I think you've verified that it's working!
