### ISSUE TITLE
Problem: pointer file creation causes unnecessary move operation

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#365]
Now that the Storage Service (SS) creates pointer files it must calculate the checksum of the AIP in order to document the checksum in the pointer file. However, this checksum creation currently happens *after* the AIP has been moved out of the SS and into its destination space. See the `_create_pointer_file_write_to_disk` method and its call to `utils.generate_checksum`. This checksum calculation calls the `fetch_local_path` method which moves the AIP back *to* the Storage Service.

Not only is the above unnecessary and inefficient, it also breaks the functionality of spaces that do not implement the `move_to_storage_service` method, such as `DSpace`.

**Comment by jrwdunham** [comment]
From a code perspective, the merging of https://github.com/artefactual/archivematica-storage-service/pull/366 fixes this issue. However, it requires QA before it can be closed.

**Comment by joel-simpson** [comment]
I have been testing Pointer file creation, and generation of the checksum in particular as a way of regression testing the fix for this issue. I haven't been able to verify that the extra 'move' operation has gone away.

To test, I have been creating and storing an AIP, then downloading the AIP and running sha256sum to generate a checksum for the AIP. I then compare the value of this checksum against the value in the pointer file. While looking at the pointer file I've also been doing a quick scan to ensure everything is present as expected. 

In the PR, @jrwdunham suggested testing a number of cases - I list these here with progress so far: 
- local filesystem, compressed AIP **(tested & verified)** 
- local filesystem, uncompressed AIP (not yet tested) 
- local filesystem, reingested AIP **(tested & verified)**
- non-local filesystem, compressed AIP **(tested and verified on an S3 storage location)**
- non-local filesystem, uncompressed AIP (not yet tested) 
- non-local filesystem, reingested AIP (not yet tested) 
this is WIP. I'll complete this next week.

**Comment by joel-simpson** [comment]
Finished testing this using AM 1.7.1 with SS qa/1.x. Verified reingested AIP stored on S3 (non-local filesystem). 
Uncompressed AIPS don't have pointer files so those test cases aren't valid. 
Moving this to 'verified'.
