### ISSUE TITLE
Problem: Dataverse docs need updating

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-storage-service#377]
Dataverse documentation needs to be updated with the latest OCUL developments on release, or slightly prior to. 

Dataverse guidelines here: https://www.archivematica.org/en/docs/storage-service-0.11/administrators/#dataverse

Related to: https://github.com/artefactual/archivematica-storage-service/issues/355

**Comment by joel-simpson** [comment]
there are a few other areas where documentation is required. I think the full list is: 

**Wiki** 
https://wiki.archivematica.org/Dataverse 
- updated with overview of workflow, gherkin etc. 
- largely done but section on METs may need to be updated

**Archivematica Documentation:** 
1) Installation - Integrations page: https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/integrations/integrations/#integrations
Needs short paragraph with link to storage service docs for configuration

2) Installation - CentOS with packages: https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/installation/install-centos/#install-pkg-centos
Nothing dataverse specific required here -- just need these pages reviewed & updated so that we can point to them when we deliver the release candidate.  

3) Transfers page: https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/transfer/transfer/#transfer
- needs a new sub page to describe Dataverse Transfers -- much like the ones for Bags, digitization etc. 
- then the main page needs a short description and link to the sub-page, in the existing "see also" box

4) AIP Structure: https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/archival-storage/aip-structure/#aip-structure
Not sure if needed - but could add minor details about where the Dataverse METS is stored, and what it's role is? 

**Storage Service Documentation** 
1) Dataverse Spaces page: 
https://www.archivematica.org/en/docs/storage-service-0.11/administrators/#dataverse

**Comment by joel-simpson** [comment]
The dataverse docs were updated with https://github.com/artefactual/archivematica-storage-service-docs/pull/10
(not sure why that PR is not showing as connected in Waffle, it should be). 
also 
https://github.com/artefactual/archivematica-docs/pull/201
These were both reviewed and approved by Sara and Ross so no need for further QA. I'm moving this issue to verified.
